[package]
name = "echocache"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { workspace = true, features = ["sync"] }
futures.workspace = true
parking_lot.workspace = true
tracing.workspace = true

[lints]
workspace = true
