on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: CI

env:
  RUSTDOCFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
        toolchain:
          - stable
          - nightly
          - beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Run cargo build
        run: cargo build --release --target ${{ matrix.target }}

  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        steps:
          - name: cargo check
            run: just check
          - name: cargo doc
            run: just doc
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: extractions/setup-just@v4
      - name: ${{ matrix.steps.name }}
        run: ${{ matrix.steps.run }}

  msrv:
    name: MSRV 1.95
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0
      - name: Run cargo build
        run: cargo check --all-targets --all-features

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - uses: extractions/setup-just@v4

      - name: Build cargo tests
        run: just test-build

      - name: Run cargo test
        run: just test-run

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
